name = "EoM_samples"
uuid = "843d7ffb-e6c5-4c2b-9337-20d6ba731113"
version = "0.1.0"
authors = ["Bruce Minaker <bminaker@uwindsor.ca>"]

[deps]
EoM = "25d7ee20-f19a-11e8-093a-7b526cbd2d90"
EoM_X3D = "29d18a9a-f19a-11e8-3142-81fd2672d0ac"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[sources]
EoM = {rev = "master", url = "https://github.com/BPMinaker/EoM.jl"}
EoM_X3D = {rev = "master", url = "https://github.com/BPMinaker/EoM_X3D.jl"}

[compat]
EoM = "2.0.0"
EoM_X3D = "0.1.0"
ForwardDiff = "1.0.1"
Interpolations = "0.16.1"
Optim = "1.13.2"
PlotlyJS = "0.18.17"
